In [21]:
#Ans1:Nominal encoding is a technique used to transform the catgorical variable into numerical variable that can be used in ml models and 
#label ecoding is a encoding to descrbe the feature acording to their  label 
#when the variable  is  catgeorical use the one hot encoding and the variable is ordianl then use the label encoding 

In [ ]:
#ANs2:It is the technique used to encode the categorical variable on their relationship with the target variable 

In [33]:
#ANs3#It is used to find the variance between two continous variable that how much one variable is vary with the other .
#FOrmula is summation i to n (xi-x(mean))(yi-y(mean)/n-1)

In [5]:
#Ans4:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [3]:
label=LabelEncoder()

In [13]:
colors=['red','green','blue']
sizes=['small','medium','large']
materials=['wood','metal','plastic']

In [14]:
pd.DataFrame(data)

color    size material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [15]:
color_label=label.fit_transform(colors)

In [16]:
size_label=label.fit_transform(sizes)

In [17]:
material_label=label.fit_transform(materials)

In [18]:
print('ENcoded colors',color_label)

ENcoded colors [2 1 0]


In [19]:
size_label

array([2, 1, 0], dtype=int64)

In [20]:
material_label

array([2, 0, 1], dtype=int64)

In [23]:
#Ans5:
import numpy as np
age = [25, 30, 35, 40, 45]
income = [50000, 60000, 70000, 80000, 90000]
education_level = [12, 14, 16, 18, 20]

In [24]:
data=np.array([age,income,education_level])

In [25]:
covaiance_matrix=np.cov(data)

In [26]:
covaiance_matrix

array([[6.25e+01, 1.25e+05, 2.50e+01],
       [1.25e+05, 2.50e+08, 5.00e+04],
       [2.50e+01, 5.00e+04, 1.00e+01]])

In [27]:
#Ans6:One hot Encoding because the variable is catgeorical

In [28]:
#Ans7:
temperature = [25, 30, 35, 40, 45]
humidity = [50, 60, 70, 80, 90]

In [29]:
data=np.array([temperature,humidity])

In [30]:
covaiance_matrix1=np.cov(data)

In [31]:
covaiance_matrix1

array([[ 62.5, 125. ],
       [125. , 250. ]])

In [32]:
#As the weather condition and wind direction is not continuous variable 