In [1]:
#Ans1:yes variable list has store simple list and array list store the array list 

In [2]:
import numpy as np
list_ = [ '1','2','3' ]
array_list = np.array( list_)

In [3]:
array_list

array(['1', '2', '3'], dtype='<U1')

In [5]:
list_

['1', '2', '3']

In [6]:
#Ans2:
list_ = [ '1','2','3','vikalp' ]

In [7]:
list_

['1', '2', '3', 'vikalp']

In [8]:
array_list = np.array( list_)

In [9]:
array_list

array(['1', '2', '3', 'vikalp'], dtype='<U6')

In [10]:
#Ans3:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array( num_list)

In [11]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [13]:
#ANs4:
num_array = np.array( num_list).shape

In [14]:
num_array

(2, 3)

In [15]:
num_array = np.array( num_list).size

In [16]:
num_array


6

In [17]:
#Ans5:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#Ans6:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])